### ISSUE TITLE
Add randomised data #62.02

### ISSUE THREAD

**Issue by elpiankova** [IonosatMicro/promis-testing#3]
Add data from Potential project to Travis

**Comment by elpiankova** [comment]
ftp://promis.ikd.kiev.ua/Potential/DECODED/

**Comment by elpiankova** [comment]
And example of satellite path

**Comment by landswellsong** [comment]
@elpiankova kindly changing the topic, the POTENTIAL data acquisition is at IonosatMicro/promis-deploy#35

**Comment by landswellsong** [comment]
The orbits generated should look like this (Mercator, but data is lon/lat):
![rplot](https://cloud.githubusercontent.com/assets/2434329/22576186/77edebe0-e9ba-11e6-9a1b-26f7080a2467.png)

(Don't ask what the hell I was smoking, kthx)
